[package]
name = "nova"
version = "0.1.0"
edition = "2021"

[dependencies]
number = { path = "../number" }
pil_analyzer = { path = "../pil_analyzer" }
num-traits = "0.2.15"
num-integer = "0.1.45"
itertools = "^0.10"
num-bigint = "^0.4"
log = "0.4.17"
rand = "0.8.5"
pasta_curves = { version = "0.5", features = ["repr-c", "serde"] }
ast = { version = "0.1.0", path = "../ast" }
nova-snark = { git = "https://github.com/hero78119/SuperNova.git", branch = "supernova", default-features = false, features = ["supernova"] }
bellperson = { version = "0.25", default-features = false}
ff = { version = "0.13.0", features = ["derive"] }
polyexen = { git = "https://github.com/Dhole/polyexen", branch = "feature/shuffles" }

[dev-dependencies]
analysis = { path = "../analysis" }
executor = { path = "../executor" }
parser = { path = "../parser" }
asm_to_pil = { path = "../asm_to_pil" }
test-log = "0.2.12"
env_logger = "0.10.0"
linker = { path = "../linker" }

